### PR TITLE
added generated DA API classes

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
switched pig to use 'em

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
@michalszynkiewicz here you go! Jenkins fought a hard battle, but in the end @thescouser89 wins

**Comment by michalszynkiewicz** [comment]
thank you Dustin!

**Comment by janinko** [comment]
Can't classes provideded by DA module `reports-model` be used?

**Comment by michalszynkiewicz** [comment]
looks like they can ;)

**Comment by michalszynkiewicz** [comment]
updated to use the `reports-model`

**Comment by michalszynkiewicz** [comment]
retest it please

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
