### PR TITLE
 PiG

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by thescouser89** [comment]
BTW you can now mark a PR as Draft on Github! https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by michalszynkiewicz** [comment]
it compiles now :D

**Comment by michalszynkiewicz** [comment]
requires https://github.com/project-ncl/pnc/pull/2323

**Comment by geoand** [comment]
Could someone give me a high level overview of what is being generated on the PNC side and what will be consumed by PiG?
I don't really understand how  project-ncl/pnc#2323 relates to PiG.
Thanks!

**Comment by michalszynkiewicz** [comment]
@geoand please take a look at `*Client` classes in `org.jboss.pnc:rest-api:java-client:2.0.0-SNAPSHOT`

The linked PR adds a way to pass query parameters to these `Client` classes.
Please ping me with any questions

**Comment by geoand** [comment]
Thanks @michalszynkiewicz ! Will do!

**Comment by geoand** [comment]
Hey! Is there any update on the PR that blocks this one? (Sorry I wasn't able to attend the latest meeting so this might have been covered there)

**Comment by michalszynkiewicz** [comment]
@geoand it's not blocked anymore, I'm working on SSL in MP Rest Client, I plan to go back to this when I finish

**Comment by geoand** [comment]
Thanks for the update @michalszynkiewicz!

**Comment by michalszynkiewicz** [comment]
replaced by https://github.com/project-ncl/cli/pull/24

**Pull request closed without merging**
